# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  Joint0:
    # has_position_limits: true
    min_position: -2.6179938780
    max_position: 2.6179938780
    has_velocity_limits: true
    max_velocity: 30
    has_acceleration_limits: false
    max_acceleration: 0
  Joint1:
    # has_position_limits: true
    min_position: -0.5235987756
    max_position: 1.0471975512
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  Joint2:
    # has_position_limits: true
    min_position: -0.6981317008
    max_position: 2.4434609528
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  Joint3:
    # has_position_limits: true
    min_position: -2.2689280276
    max_position: 2.2689280276
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0